// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xbostgpatumfcxwpfgqq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhib3N0Z3BhdHVtZmN4d3BmZ3FxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0Mzg3NzYsImV4cCI6MjA2MDAxNDc3Nn0.UeWKP6yfr8p8ZNyF-olhJKOwH3mRZNmEU7gcCTWxG3c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);